### ISSUE TITLE
Partition disappeared after an ejection

### ISSUE THREAD

**Issue by mysecret-glitch** [TheyKilledKenny/Emutool#2]
![image](https://user-images.githubusercontent.com/81695012/114726696-936d9200-9d78-11eb-8d56-03e5201fc89e.png)

1. Tried convert atmosphere file to atmosphere hidden partition
2. Converting seemed to be successful
3. Copied Nintendo folder to the new location on SD
4. Eject
5. Inserted SD into Switch and found out Hekate couldn't boot into Atmosphere
6. Inserted SD into PC and found out there is no partition on SD

I have only emummc backup (not a whole SD backup). how can I recover the partition? Is there any chance I got?

**Comment by mysecret-glitch** [comment]
I managed to recover the partition by using [testdisk](https://www.cgsecurity.org/wiki/TestDisk_Download)
however, I have no idea why this happened.

**Comment by TheyKilledKenny** [comment]
Emutool has no partitioning function, so it cannot create or even delete partitions by extending the pre-existing ones. From your image it seems that you have formatted the sd with some tool (like SD formatter?) completely deleting all partitions.
Emutool does not take into account the partitioning of the card, but writes directly to the SD starting from the sector number entered.
Before restoring to a partition you need to prepare the 29 / 30GB partition on your SD card and note the sector number.
