### ISSUE TITLE
this

### ISSUE THREAD

**Issue by OldGnashburg** [TheyKilledKenny/Emutool#3]
I have 2 partition Atmosphere EmuNAND's I want to convert one to a SX OS partition EmuNAND, but this tool has that option greyed out when I select the source as an Atmosphere EmuNAND. Does your tool not allow for this?

**Comment by TheyKilledKenny** [comment]
You can convert between Files Emu and Hidden Partition Emu, not between hidden partitions emu.
If you want to migrate the emu on the same sd card then you first have to copy Atmosphere emu to files emu to your pc (atmosphere or sxos is the same) using Emutool, then you have to correctly repartition the sd card manually. Emutool does not create partitions.
You can create a correct partitioning using sxos menu to start a new hidden partition Emunand creation and stopping it very soon whe you see boot0 or boot1, in this moment the correct partitioning should be on your sd.
When the sd have the correct partitionning you can use Emutool to copy/convert from the files emu you created on your PC to sxos hidden partition to sd.
Same if you're using two sd card, first backup to files emu on your pc and then restore on sxos sd card.

You may probably want to use sxos with an emu on file, in this case you can, in only one step, convert your Atmosphere hidden partition emu to sxos files emu and copy the obtained files to the sxos/Emunand folder on your sdcard.
If you want to keep all the installed softwares, remember to copy the Nintendo folder from Atmosphere emu (normally you can find it in emummc/raw01/  folder) to sd root and rename it in Emutendo (warning, normally this is a very big folder if you have a lot of software installed).
